# This file was generated by GoReleaser. DO NOT EDIT.
cask "resumer" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "e29509d6479f1824812797f725934fd9a20a161eb99d303b8959a4c87beb01a7"
      url "https://github.com/jin-ttao/resumer/releases/download/v#{version}/resumer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0906f99acab427d3682bd7077c2def3eac96989dcc89d258c9d779cb5fde497f"
      url "https://github.com/jin-ttao/resumer/releases/download/v#{version}/resumer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0d5a7fff4217f81bbe7c984f066c03050065d4a1e7300c48d3ef9f6dd222b7be"
      url "https://github.com/jin-ttao/resumer/releases/download/v#{version}/resumer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c59ec982e3b3b23595a9c6d5a840e30ed424849a613ebd5e071aec5e538f2362"
      url "https://github.com/jin-ttao/resumer/releases/download/v#{version}/resumer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "resumer"
  desc "Browse & resume your Claude Code / Codex sessions"
  homepage "https://github.com/jin-ttao/resumer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "resumer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/resumer"]
    end
  end

end
